import { Pool, type PoolClient } from "pg";

const POOL_MAX = 5;

export type Gift = {
  id: number;
  slug: string;
  name: string;
  description: string;
  image_key: string;
  amount_cents: number;
  total_quantity: number;
  sold_quantity: number;
  category: string;
  display_order: number;
  active: number;
  created_at: string;
  updated_at: string;
};

export type PaymentStatus = "pending" | "paid" | "expired" | "cancelled" | "failed";

export type Payment = {
  id: number;
  public_id: string;
  gift_id: number;
  provider: string;
  provider_charge_id: string | null;
  amount_cents: number;
  status: PaymentStatus;
  pix_code: string | null;
  error: string | null;
  expires_at: string | null;
  paid_at: string | null;
  claimed_at: string | null;
  confirmed_by_admin: number;
  oversold: number;
  created_at: string;
  updated_at: string;
};

export type PhotoStatus = "received" | "uploading" | "uploaded" | "failed";

export type PhotoUpload = {
  id: number;
  public_id: string;
  original_filename: string;
  mime_type: string;
  size_bytes: number;
  storage_provider: string;
  storage_key: string | null;
  staging_key: string | null;
  external_id: string | null;
  status: PhotoStatus;
  error: string | null;
  hidden: number;
  created_at: string;
  uploaded_at: string | null;
};

export type AdminSession = {
  id: number;
  token_hash: string;
  created_at: string;
  expires_at: string;
};

const SCHEMA = `
CREATE TABLE IF NOT EXISTS gifts (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  image_key text NOT NULL DEFAULT 'default',
  amount_cents integer NOT NULL CHECK (amount_cents >= 0),
  total_quantity integer NOT NULL DEFAULT 1 CHECK (total_quantity >= 0),
  sold_quantity integer NOT NULL DEFAULT 0 CHECK (sold_quantity >= 0),
  category text NOT NULL DEFAULT 'Momentos da festa',
  display_order integer NOT NULL DEFAULT 0,
  active integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS payments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id text NOT NULL UNIQUE,
  gift_id integer NOT NULL REFERENCES gifts(id),
  provider text NOT NULL,
  provider_charge_id text UNIQUE,
  amount_cents integer NOT NULL CHECK (amount_cents >= 0),
  status text NOT NULL DEFAULT 'pending',
  pix_code text,
  error text,
  expires_at timestamptz,
  paid_at timestamptz,
  claimed_at timestamptz,
  confirmed_by_admin integer NOT NULL DEFAULT 0,
  oversold integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS payments_gift_idx ON payments(gift_id);
CREATE INDEX IF NOT EXISTS payments_status_idx ON payments(status);

CREATE TABLE IF NOT EXISTS payment_events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id integer REFERENCES payments(id),
  provider_event_id text NOT NULL UNIQUE,
  event_type text NOT NULL,
  payload text NOT NULL,
  received_at timestamptz NOT NULL DEFAULT now(),
  processed_at timestamptz
);

CREATE TABLE IF NOT EXISTS photo_uploads (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id text NOT NULL UNIQUE,
  original_filename text NOT NULL,
  mime_type text NOT NULL,
  size_bytes integer NOT NULL,
  storage_provider text NOT NULL DEFAULT 'local',
  storage_key text,
  staging_key text,
  external_id text,
  status text NOT NULL DEFAULT 'received',
  error text,
  hidden integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  uploaded_at timestamptz
);

CREATE TABLE IF NOT EXISTS admin_sessions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_hash text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS settings (
  key text PRIMARY KEY,
  value text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);
`;

type GlobalWithPool = typeof globalThis & {
  __deixaAquiPool?: Pool;
  __deixaAquiReady?: Promise<void>;
  __deixaAquiDb?: Db;
};

export type RunResult = {
  rowCount: number;
  rows: Record<string, unknown>[];
};

type Params = Record<string, unknown>;

function translate(sql: string, params: unknown[] | Params | undefined) {
  if (params === undefined) return { text: sql, values: [] as unknown[] };

  if (Array.isArray(params)) {
    let index = 0;
    return { text: sql.replace(/\?/g, () => `$${++index}`), values: params };
  }

  const seen = new Map<string, number>();
  const values: unknown[] = [];
  const text = sql.replace(/@([A-Za-z_][A-Za-z0-9_]*)/g, (_match, name: string) => {
    const found = seen.get(name);
    if (found !== undefined) return `$${found}`;
    values.push(params[name] ?? null);
    const index = values.length;
    seen.set(name, index);
    return `$${index}`;
  });
  return { text, values };
}

function normalize(row: Record<string, unknown>) {
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(row)) {
    out[key] = value instanceof Date ? value.toISOString() : value;
  }
  return out;
}

type Executor = Pick<Pool, "query"> | Pick<PoolClient, "query">;

type Statement<Args extends unknown[], R> = {
  get(...args: [...Args] | [Params]): Promise<R | undefined>;
  all(...args: [...Args] | [Params]): Promise<R[]>;
  run(...args: [...Args] | [Params]): Promise<RunResult>;
};

export type Db = {
  prepare<Args extends unknown[] = unknown[], R = Record<string, unknown>>(
    sql: string,
  ): Statement<Args, R>;
  transaction<T>(fn: (db: Db) => Promise<T>): Promise<T>;
};

function makeDb(executor: Executor): Db {
  const db: Db = {
    prepare(sql) {
      const send = async (params: unknown[] | Params | undefined) => {
        const { text, values } = translate(sql, params);
        return executor.query(text, values);
      };

      return {
        async get(params?: unknown[] | Params) {
          const result = await send(params);
          return result.rows[0] ? normalize(result.rows[0]) : undefined;
        },
        async all(params?: unknown[] | Params) {
          const result = await send(params);
          return result.rows.map(normalize);
        },
        async run(params?: unknown[] | Params) {
          const result = await send(params);
          return { rowCount: result.rowCount ?? 0, rows: result.rows.map(normalize) };
        },
      } as never;
    },

    async transaction(fn) {
      const pool = getPool();
      const client = await pool.connect();
      try {
        await client.query("BEGIN");
        const result = await fn(makeDb(client));
        await client.query("COMMIT");
        return result;
      } catch (error) {
        await client.query("ROLLBACK").catch(() => undefined);
        throw error;
      } finally {
        client.release();
      }
    },
  };
  return db;
}

function getPool(): Pool {
  const scope = globalThis as GlobalWithPool;
  if (!scope.__deixaAquiPool) {
    const connectionString = process.env.DATABASE_URL;
    if (!connectionString) {
      throw new Error("DATABASE_URL nao configurada: o app depende do Postgres do Neon");
    }
    scope.__deixaAquiPool = new Pool({
      connectionString,
      max: POOL_MAX,
      idleTimeoutMillis: 10_000,
    });
  }
  return scope.__deixaAquiPool;
}

function columnExists(executor: Executor, table: string, column: string) {
  return executor
    .query(
      `SELECT 1 FROM information_schema.columns
       WHERE table_schema = 'public' AND table_name = $1 AND column_name = $2`,
      [table, column],
    )
    .then((result) => result.rowCount !== 0);
}

async function migrate(executor: Executor) {
  const additions: [string, string, string][] = [
    ["gifts", "total_quantity", "integer NOT NULL DEFAULT 1"],
    ["gifts", "sold_quantity", "integer NOT NULL DEFAULT 0"],
    ["payments", "oversold", "integer NOT NULL DEFAULT 0"],
  ];
  for (const [table, column, definition] of additions) {
    if (!(await columnExists(executor, table, column))) {
      await executor.query(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`);
    }
  }
}

type SeedGift = {
  slug: string;
  name: string;
  description: string;
  image_key: string;
  amount_cents: number;
  category: string;
  total_quantity?: number;
};

const SEED_GIFTS: SeedGift[] = [
  {
    slug: "primeiro-chopp-da-noiva",
    total_quantity: 3,
    name: "Primeiro Chop da Noiva",
    description: "Porque todo grande momento merece um primeiro brinde.",
    image_key: "chopp",
    amount_cents: 8000,
    category: "Momentos da festa",
  },
  {
    slug: "ultimo-chopp-das-noivas",
    total_quantity: 2,
    name: "Último Chop das Noivas",
    description: "O brinde que encerra a noite. Ninguém precisa lembrar disso depois.",
    image_key: "chopp",
    amount_cents: 9000,
    category: "Momentos da festa",
  },
  {
    slug: "brinde-que-ninguem-deveria-tomar",
    total_quantity: 3,
    name: "Aquele Brinde que Ninguém Deveria Tomar",
    description: "Já sabemos como termina. Mesmo assim, ninguém recusa.",
    image_key: "brinde",
    amount_cents: 6000,
    category: "Momentos da festa",
  },
  {
    slug: "sobremesa-das-noivas",
    total_quantity: 2,
    name: "Sobremesa das Noivas",
    description: "A parte mais doce da noite, dividida com você.",
    image_key: "sobremesa",
    amount_cents: 7000,
    category: "Momentos da festa",
  },
  {
    slug: "fundo-emergencial-do-open-bar",
    total_quantity: 2,
    name: "Fundo Emergencial do Open Bar",
    description: "Segurança para o balcão não fechar antes da valsa.",
    image_key: "openbar",
    amount_cents: 25000,
    category: "Presentes perigosamente específicos",
  },
  {
    slug: "terapia-pos-casamento",
    total_quantity: 2,
    name: "Terapia Pós-Casamento",
    description: "Um investimento bem bureaucraticamente correto para o ano que vem.",
    image_key: "terapia",
    amount_cents: 15000,
    category: "Presentes perigosamente específicos",
  },
  {
    slug: "combustivel-para-a-volta",
    total_quantity: 2,
    name: "Combustível para a Volta",
    description: "Para a noite não acabar antes de vocês chegarem em casa.",
    image_key: "combustivel",
    amount_cents: 20000,
    category: "Presentes perigosamente específicos",
  },
  {
    slug: "eu-avisei-que-ia-gastar",
    total_quantity: 2,
    name: "Eu Avisei que Ia Gastar",
    description: "Você avisou. A gente anotou. Agora é sua vez de repassar a conta.",
    image_key: "aviso",
    amount_cents: 10000,
    category: "Presentes perigosamente específicos",
  },
  {
    slug: "brinde-as-noivas",
    total_quantity: 5,
    name: "Um Brinde às Noivas",
    description: "Para o jogo de transformar uma noite em memória.",
    image_key: "brinde",
    amount_cents: 5000,
    category: "Nossa história",
  },
  {
    slug: "pedacinho-da-lua-de-mel",
    total_quantity: 2,
    name: "Um Pedacinho da Nossa Lua de Mel",
    description: "Ajuda a comprar a lua de mel que a gente vai contar pra todo mundo.",
    image_key: "lua",
    amount_cents: 30000,
    category: "Nossa história",
  },
  {
    slug: "experiencia-em-curitiba",
    total_quantity: 1,
    name: "Uma Experiência em Curitiba",
    description: "Um passeio a três, do jeito que a gente sempre quis fazer.",
    image_key: "curitiba",
    amount_cents: 25000,
    category: "Nossa história",
  },
];

const SEED_SETTINGS: Record<string, string> = {
  wedding_names: process.env.WEDDING_NAMES || "Jéssica & Jennifer",
  wedding_date: process.env.WEDDING_DATE || "2026-10-29",
  hero_title: "Nosso dia fica ainda mais especial porque você está aqui.",
  story_title: "Nossa história",
  story_text:
    "A gente se conheceu num dia comum, num lugar comum, e nenhuma das duas fez a primeira escolha certa. A vida deu algumas voltas antes de colocar a gente exatamente onde deveria estar: uma com a outra.\n\nEste site não é uma lista de casamento. É um cantinho do nosso dia, feito para quem esteve aqui — ou fez parte da nossa história — deixar um pedacinho seu com a gente.\n\nPode ser um presente, uma foto, uma memória. No fim, a gente só queria guardar um pouco de tudo aquilo que fez esse dia ser nosso.",
  pix_recipient_name: process.env.WEDDING_NAMES || "Jéssica & Jennifer",
  pix_key: process.env.PIX_KEY || "",
  pix_recipient_city: process.env.PIX_RECIPIENT_CITY || "SAO PAULO",
  site_active: "1",
  photo_storage: process.env.PHOTO_STORAGE || "local",
  pix_provider: process.env.PIX_PROVIDER || "manual",
  google_drive_folder_id: process.env.GOOGLE_DRIVE_FOLDER_ID || "1BxFLKSC8o0MezlAuuewodhnto1EMSz_o",
};

async function seed(executor: Executor) {
  const gifts: string[] = [];
  const values: unknown[] = [];
  SEED_GIFTS.forEach((gift, index) => {
    values.push(
      gift.slug,
      gift.name,
      gift.description,
      gift.image_key,
      gift.amount_cents,
      gift.category,
      (index + 1) * 10,
      gift.total_quantity ?? 1,
    );
    const base = values.length - 8;
    gifts.push(
      `($${base + 1}, $${base + 2}, $${base + 3}, $${base + 4}, $${base + 5}, $${base + 6}, $${base + 7}, $${base + 8})`,
    );
  });
  await executor.query(
    `INSERT INTO gifts
       (slug, name, description, image_key, amount_cents, category, display_order, total_quantity)
     VALUES ${gifts.join(", ")}
     ON CONFLICT (slug) DO NOTHING`,
    values,
  );

  const settings = Object.entries(SEED_SETTINGS);
  if (settings.length > 0) {
    const rows: string[] = [];
    const params: unknown[] = [];
    settings.forEach(([key, value], index) => {
      params.push(key, value);
      rows.push(`($${index * 2 + 1}, $${index * 2 + 2})`);
    });
    await executor.query(
      `INSERT INTO settings (key, value) VALUES ${rows.join(", ")}
       ON CONFLICT (key) DO NOTHING`,
      params,
    );
  }
}

function ready(): Promise<void> {
  const scope = globalThis as GlobalWithPool;
  if (!scope.__deixaAquiReady) {
    scope.__deixaAquiReady = (async () => {
      const executor = getPool();
      await executor.query(SCHEMA);
      await migrate(executor);
      await seed(executor);
    })().catch((error) => {
      scope.__deixaAquiReady = undefined;
      throw error;
    });
  }
  return scope.__deixaAquiReady;
}

export function getDb(): Db {
  const scope = globalThis as GlobalWithPool;
  if (!scope.__deixaAquiDb) {
    const db = makeDb({
      query: (text: string, values?: unknown[]) => {
        const pending = ready().then(() => getPool().query(text, values as never[]));
        return pending as never;
      },
    } as Executor);
    scope.__deixaAquiDb = db;
  }
  return scope.__deixaAquiDb!;
}